version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  bot:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      WEBHOOK_URL: ${WEBHOOK_URL}
      BOT_TOKEN: ${BOT_TOKEN}
